package com.avasaysayava.bagrutproject.game.graphic.gamemap.levelmap;

import com.avasaysayava.bagrutproject.game.Game;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class Level2Map extends LevelMap {
    @SuppressWarnings("unchecked")
    public Level2Map(Game game) {
        super(game,
                new List[][]{
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(10).withZ(1)),
                        },
                        new List[]{
                                Collections.emptyList(),
                                Arrays.asList(game.groundTileSet.getTile(62).withZ(1), game.wallsTileSet.getTile(0).withZ(1)),
                                Arrays.asList(game.groundTileSet.getTile(11).withZ(1), game.wallsTileSet.getTile(1).withZ(1)),
                                Arrays.asList(game.groundTileSet.getTile(24).withZ(1), game.wallsTileSet.getTile(1).withZ(1), game.structuresTileSet.getTile(16).withZ(1)),
                                Arrays.asList(game.groundTileSet.getTile(16).withZ(1), game.wallsTileSet.getTile(1).withZ(1)),
                                Arrays.asList(game.groundTileSet.getTile(4).withZ(1), game.wallsTileSet.getTile(1).withZ(1)),
                                Arrays.asList(game.groundTileSet.getTile(12).withZ(1), game.wallsTileSet.getTile(1).withZ(1), game.structuresTileSet.getTile(0).withZ(1)),
                                Arrays.asList(game.groundTileSet.getTile(29).withZ(1), game.wallsTileSet.getTile(1).withZ(1)),
                                Arrays.asList(game.groundTileSet.getTile(63).withZ(1), game.wallsTileSet.getTile(2).withZ(1)),
                        },
                        new List[]{
                                Collections.emptyList(),
                                Arrays.asList(game.groundTileSet.getTile(30).withZ(1), game.wallsTileSet.getTile(13).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(20).withZ(1)),
                                Arrays.asList(game.groundTileSet.getTile(21).withZ(1), game.structuresTileSet.getTile(21).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(22).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(23).withZ(1)),
                                Arrays.asList(game.groundTileSet.getTile(24).withZ(1), game.structuresTileSet.getTile(5).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(25).withZ(1)),
                                Arrays.asList(game.groundTileSet.getTile(11).withZ(1), game.wallsTileSet.getTile(14).withZ(1)),
                        },
                        new List[]{
                                Collections.emptyList(),
                                Arrays.asList(game.groundTileSet.getTile(12).withZ(1), game.wallsTileSet.getTile(13).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(55).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(33).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(38).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(39).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(32).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(54).withZ(1)),
                                Arrays.asList(game.groundTileSet.getTile(25).withZ(1), game.wallsTileSet.getTile(14).withZ(1)),
                        },
                        new List[]{
                                Collections.emptyList(),
                                Arrays.asList(game.groundTileSet.getTile(25).withZ(1), game.wallsTileSet.getTile(13).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(53).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(45).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(40).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(32).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(47).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(52).withZ(1)),
                                Arrays.asList(game.groundTileSet.getTile(16).withZ(1), game.wallsTileSet.getTile(14).withZ(1)),
                        },
                        new List[]{
                                Collections.emptyList(),
                                Arrays.asList(game.groundTileSet.getTile(7).withZ(1), game.wallsTileSet.getTile(13).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(15).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(11).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(53).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(52).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(10).withZ(1)),
                                Collections.singletonList(game.groundTileSet.getTile(12).withZ(1)),
                                Arrays.asList(game.groundTileSet.getTile(4).withZ(1), game.wallsTileSet.getTile(14).withZ(1)),
                        },
                        new List[]{
                                Arrays.asList(game.groundTileSet.getTile(62).withZ(0), game.wallsTileSet.getTile(0).withZ(0)),
                                Arrays.asList(game.groundTileSet.getTile(0).withZ(0), game.wallsTileSet.getTile(22).withZ(0), game.wallsTileSet.getTile(52).withZ(1)),
                                Arrays.asList(game.wallsTileSet.getTile(36).withZ(0), game.wallsTileSet.getTile(53).withZ(1)),
                                Arrays.asList(game.wallsTileSet.getTile(37).withZ(0), game.wallsTileSet.getTile(54).withZ(1)),
                                Arrays.asList(game.wallsTileSet.getTile(74).withZ(0), game.wallsTileSet.getTile(83).withZ(1)),
                                Arrays.asList(game.wallsTileSet.getTile(75).withZ(0), game.wallsTileSet.getTile(82).withZ(1)),
                                Arrays.asList(game.wallsTileSet.getTile(4).withZ(0), game.wallsTileSet.getTile(42).withZ(1)),
                                Arrays.asList(game.wallsTileSet.getTile(39).withZ(0), game.wallsTileSet.getTile(56).withZ(1)),
                                Arrays.asList(game.groundTileSet.getTile(0).withZ(0), game.wallsTileSet.getTile(24).withZ(0), game.wallsTileSet.getTile(57).withZ(1)),
                                Arrays.asList(game.groundTileSet.getTile(63).withZ(0), game.wallsTileSet.getTile(2).withZ(0)),
                        },
                        new List[]{
                                Arrays.asList(game.groundTileSet.getTile(23).withZ(0), game.wallsTileSet.getTile(13).withZ(0)),
                                Arrays.asList(game.groundTileSet.getTile(0).withZ(0), game.wallsTileSet.getTile(29).withZ(0)),
                                Collections.singletonList(game.wallsTileSet.getTile(47).withZ(0)),
                                Arrays.asList(game.groundTileSet.getTile(0).withZ(0), game.wallsTileSet.getTile(48).withZ(0)),
                                Arrays.asList(game.wallsTileSet.getTile(85).withZ(0), game.wallsTileSet.getTile(92).withZ(0)),
                                Arrays.asList(game.wallsTileSet.getTile(86).withZ(0), game.wallsTileSet.getTile(91).withZ(0)),
                                Collections.singletonList(game.wallsTileSet.getTile(15).withZ(0)),
                                Collections.singletonList(game.wallsTileSet.getTile(50).withZ(0)),
                                Arrays.asList(game.groundTileSet.getTile(0).withZ(0), game.wallsTileSet.getTile(31).withZ(0)),
                                Arrays.asList(game.groundTileSet.getTile(24).withZ(0), game.wallsTileSet.getTile(14).withZ(0)),
                        },
                        new List[]{
                                Arrays.asList(game.groundTileSet.getTile(27).withZ(0), game.wallsTileSet.getTile(13).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(28).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(29).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(30).withZ(0)),
                                Arrays.asList(game.wallsTileSet.getTile(94).withZ(0), game.wallsTileSet.getTile(101).withZ(0)),
                                Arrays.asList(game.wallsTileSet.getTile(95).withZ(0), game.wallsTileSet.getTile(100).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(31).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(26).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(25).withZ(0)),
                                Arrays.asList(game.groundTileSet.getTile(10).withZ(0), game.wallsTileSet.getTile(14).withZ(0)),
                        },
                        new List[]{
                                Arrays.asList(game.groundTileSet.getTile(16).withZ(0), game.wallsTileSet.getTile(13).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(17).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(18).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(19).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(55).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(54).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(22).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(23).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(24).withZ(0)),
                                Arrays.asList(game.groundTileSet.getTile(10).withZ(0), game.wallsTileSet.getTile(14).withZ(0)),
                        },
                        new List[]{
                                Arrays.asList(game.groundTileSet.getTile(58).withZ(0), game.wallsTileSet.getTile(13).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(2).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(37).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(36).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(56).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(57).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(39).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(38).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(7).withZ(0)),
                                Arrays.asList(game.groundTileSet.getTile(10).withZ(0), game.wallsTileSet.getTile(14).withZ(0)),
                        },
                        new List[]{
                                Arrays.asList(game.groundTileSet.getTile(11).withZ(0), game.wallsTileSet.getTile(13).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(9).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(45).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(41).withZ(0)),
                                Arrays.asList(game.groundTileSet.getTile(0).withZ(0), game.glyphFloorTileSet.getTile(24).withZ(0)),
                                Arrays.asList(game.groundTileSet.getTile(0).withZ(0), game.glyphFloorTileSet.getTile(26).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(33).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(46).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(11).withZ(0)),
                                Arrays.asList(game.groundTileSet.getTile(23).withZ(0), game.wallsTileSet.getTile(14).withZ(0)),
                        },
                        new List[]{
                                Arrays.asList(game.groundTileSet.getTile(11).withZ(0), game.wallsTileSet.getTile(13).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(12).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(13).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(14).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(15).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(16).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(17).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(18).withZ(0)),
                                Collections.singletonList(game.groundTileSet.getTile(19).withZ(0)),
                                Arrays.asList(game.groundTileSet.getTile(20).withZ(0), game.wallsTileSet.getTile(14).withZ(0)),
                        },
                        new List[]{
                                Collections.singletonList(game.wallsTileSet.getTile(41).withZ(0)),
                                Collections.singletonList(game.wallsTileSet.getTile(43).withZ(0)),
                                Collections.singletonList(game.wallsTileSet.getTile(44).withZ(0)),
                                Collections.singletonList(game.wallsTileSet.getTile(43).withZ(0)),
                                Collections.singletonList(game.wallsTileSet.getTile(45).withZ(0)),
                                Collections.singletonList(game.wallsTileSet.getTile(56).withZ(0)),
                                Collections.singletonList(game.wallsTileSet.getTile(53).withZ(0)),
                                Collections.singletonList(game.wallsTileSet.getTile(44).withZ(0)),
                                Collections.singletonList(game.wallsTileSet.getTile(45).withZ(0)),
                                Collections.singletonList(game.wallsTileSet.getTile(57).withZ(0)),
                        },
                        new List[]{}
                },
                32,
                32 * -4.5f,
                32 * -8.75f
        );
    }
}
