@startuml
class service.BackgroundMusicService {
- MediaPlayer player
+ IBinder onBind(Intent)
+ int onStartCommand(Intent,int,int)
+ void onDestroy()
}




android.app.Service <|- service.BackgroundMusicService
@enduml