@startuml
'https://plantuml.com/object-diagram

object StartActivity
object HowToPlayActivity
object CreditsActivity
object MenuActivity
object LevelActivity

StartActivity <---> MenuActivity
StartActivity <---> CreditsActivity
StartActivity <---> HowToPlayActivity
MenuActivity <---> LevelActivity
@enduml
