package com.avasaysayava.bagrutproject.game.graphic.gamemap.debugmap;

import com.avasaysayava.bagrutproject.game.Game;

import java.util.Collections;
import java.util.List;

public class StructuresMap extends DebugMap {
    @SuppressWarnings("unchecked")
    public StructuresMap(Game game, float x, float y) {
        super(
                game,
                new List[][]{
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(0)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(1)),
                                Collections.singletonList(game.structuresTileSet.getTile(2)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(3)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(4))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(5)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(6)),
                                Collections.singletonList(game.structuresTileSet.getTile(7)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(8)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(9))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(10)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(11)),
                                Collections.singletonList(game.structuresTileSet.getTile(12)),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(13)),
                                Collections.singletonList(game.structuresTileSet.getTile(14)),
                                Collections.singletonList(game.structuresTileSet.getTile(15))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(16)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(17)),
                                Collections.singletonList(game.structuresTileSet.getTile(18)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(19)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(20))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(21)),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(22)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(23))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(24)),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(25)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(26)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(27))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(28)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(29)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(30)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(31))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(32)),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(33)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(34)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(35)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(36))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(37)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(38)),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(39)),
                                Collections.singletonList(game.structuresTileSet.getTile(40)),
                                Collections.singletonList(game.structuresTileSet.getTile(41))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(42)),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(43)),
                                Collections.singletonList(game.structuresTileSet.getTile(44)),
                                Collections.singletonList(game.structuresTileSet.getTile(45))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(46)),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(47)),
                                Collections.singletonList(game.structuresTileSet.getTile(48)),
                                Collections.singletonList(game.structuresTileSet.getTile(49))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(50)),
                                Collections.singletonList(game.structuresTileSet.getTile(51))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.structuresTileSet.getTile(52)),
                                Collections.singletonList(game.structuresTileSet.getTile(53))
                        }
                },
                32,
                x,
                y
        );
    }
}
