@startuml
class com.avasaysayava.bagrutproject.activity.HowToPlayActivity {
- Button btn_back
- MediaPlayer click
- MediaPlayer load
# void onCreate(Bundle)
}




android.app.Activity <|-- com.avasaysayava.bagrutproject.activity.HowToPlayActivity
@enduml