@startuml
class game.gui.Joystick {
- float radius
- Paint innerPaint
- Paint outerPaint
- float X
- float Y
# float outerX
# float outerY
# float innerX
# float innerY
- boolean enabled
+ <<Create>> Joystick(Level,float,float,float)
+ void draw(Canvas)
# void arrange()
+ double getDistance(MotionEvent)
+ double getDistance()
+ double getPercentage()
+ double getRadians()
+ double getAngle()
+ double getSin()
+ double getCos()
+ boolean isPressed(MotionEvent)
+ void enable(MotionEvent)
+ void disable()
+ boolean isEnabled()
+ void reset()
+ void press(MotionEvent)
+ float getRadius()
}


@enduml