@startuml
class game.entity.Shadow {
- Tile tile
- Entity entity
+ <<Create>> Shadow(Level,Entity,Tile)
+ void draw(Canvas)
+ void update()
+ Collision getCollision()
+ int getLeft()
+ int getDown()
+ Shadow getShadow()
+ int getZ()
+ void setZ(int)
+ Point getCords()
}




game.entity.Entity <|- game.entity.Shadow
@enduml