@startuml
class game.graphic.tileset.GlyphFloorTileSet {
+ <<Create>> GlyphFloorTileSet(Context)
# Tile[] getTileArray()
}



game.graphic.tileset.TileSet <|-- game.graphic.tileset.GlyphFloorTileSet
@enduml