@startuml
class game.property.GlyphStoneProperty {
+ {static} int GLYPH_GOAL
- int glyphs
- Tile tile
+ <<Create>> GlyphStoneProperty(Game,GameMap,Tile,int,int)
+ void update(Entity)
+ Tile getTile()
}




game.property.Property <|-- game.property.GlyphStoneProperty
@enduml