@startuml
class game.property.GlyphProperty {
- Tile tile
+ <<Create>> GlyphProperty(Game,GameMap,Tile,int,int)
+ void update(Entity)
+ Tile getTile()
}




game.property.Property <|-- game.property.GlyphProperty
@enduml