@startuml
class game.property.StairUpProperty {
+ <<Create>> StairUpProperty(Game,GameMap,Tile,int,int)
+ void update(Entity)
+ Tile getTile()
}



game.property.Property <|-- game.property.StairUpProperty
@enduml