@startuml
abstract class database.datasource.DataSource {
# DatabaseHelper databaseHelper
# Context context
# SQLiteDatabase database
+ <<Create>> DataSource(Context)
+ void openWriteable()
+ void openReadable()
+ void close()
}


@enduml