@startuml
class database.datasource.LevelDataSource {
- String LEVEL_NAME
+ <<Create>> LevelDataSource(Context,String)
+ String getTimeByUUID(String)
+ void setLevel(String)
+ int getRankByUUID(String)
+ void updateTimeByUUID(String,String)
+ String getTimeByRank(int)
}




database.datasource.DataSource <|- database.datasource.LevelDataSource
@enduml