@startuml
class database.datasource.UUIDDataSource {
- String PREFS_NAME
- String UUID_PREF_NAME
+ <<Create>> UUIDDataSource(Context)
+ void insertUUID(String)
+ boolean UUIDExists(String)
+ void saveUUID(String)
+ String getUUID()
- String generateUUID()
+ void updateUUID()
}




database.datasource.DataSource <|- database.datasource.UUIDDataSource
@enduml