package com.avasaysayava.bagrutproject.game.graphic.gamemap;

import com.avasaysayava.bagrutproject.game.Game;

import java.util.Collections;
import java.util.List;

public class PropsMap extends GameMap {
    @SuppressWarnings("unchecked")
    public PropsMap(Game game, float x, float y) {
        super(
                game,
                new List[][]{
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(0)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(1)),
                                Collections.singletonList(game.propsTileSet.getTile(2)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(3)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(4))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(5)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(6)),
                                Collections.singletonList(game.propsTileSet.getTile(7)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(8)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(9))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(10)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(11)),
                                Collections.singletonList(game.propsTileSet.getTile(12)),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(13)),
                                Collections.singletonList(game.propsTileSet.getTile(14)),
                                Collections.singletonList(game.propsTileSet.getTile(15))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(16)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(17)),
                                Collections.singletonList(game.propsTileSet.getTile(18)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(19)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(20))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(21)),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(22)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(23))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(24)),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(25)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(26)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(27))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(28)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(29)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(30)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(31))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(32)),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(33)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(34)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(35)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(36))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(37)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(38)),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(39)),
                                Collections.singletonList(game.propsTileSet.getTile(40)),
                                Collections.singletonList(game.propsTileSet.getTile(41))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(42)),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(43)),
                                Collections.singletonList(game.propsTileSet.getTile(44)),
                                Collections.singletonList(game.propsTileSet.getTile(45))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(46)),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(47)),
                                Collections.singletonList(game.propsTileSet.getTile(48)),
                                Collections.singletonList(game.propsTileSet.getTile(49))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(50)),
                                Collections.singletonList(game.propsTileSet.getTile(51))
                        },
                        new List[]{
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.emptyList(),
                                Collections.singletonList(game.propsTileSet.getTile(52)),
                                Collections.singletonList(game.propsTileSet.getTile(53))
                        }
                },
                32,
                x,
                y
        );
    }
}
