@startuml
class com.avasaysayava.bagrutproject.database.DatabaseHelper {
- {static} String DATABASE_NAME
- {static} int DATABASE_VERSION
- {static} String SQL_CREATE_ENTRIES
- {static} String SQL_DELETE_ENTRIES
+ <<Create>> DatabaseHelper(Context)
+ void onCreate(SQLiteDatabase)
+ void onUpgrade(SQLiteDatabase,int,int)
}




android.database.sqlite.SQLiteOpenHelper <|- com.avasaysayava.bagrutproject.database.DatabaseHelper
@enduml