@startuml
class database.DatabaseContract {
}
class database.UserEntry {
+ {static} String TABLE_NAME
+ {static} String COLUMN_UUID
+ {static} String COLUMN_LEVEL1
+ {static} String COLUMN_LEVEL2
+ {static} String COLUMN_LEVEL3
+ {static} String COLUMN_LEVEL4
+ {static} String COLUMN_LEVEL5
+ {static} String COLUMN_LEVEL6
+ {static} String COLUMN_LEVEL7
+ {static} String COLUMN_LEVEL8
+ {static} String COLUMN_LEVEL9
}



database.DatabaseContract +. database.UserEntry
android.provider.BaseColumns <|. database.UserEntry
@enduml